### ISSUE TITLE
Service Requirements are out of date

### ISSUE THREAD

**Issue by Relequestual** [MatchmakerExchange/matchmakerexchange.github.io#52]
The [Matchmaker Exchange Service Requirements April2017](http://www.matchmakerexchange.org/assets/files/Matchmaker.Exchange.Service.Requirements_April2017.pdf) are out of date.

The new link is https://www.ga4gh.org/docs/ga4ghtoolkit/data-security/2016May10_REV_SecInfrastructure.pdf

As we're updating it, we should include something about the new optional `terms` field. Something along the lines of, it should be shown to the user with the data, if provided, along with the disclaimer.

**Comment by dazzariti** [comment]
Thanks Ben. I've updated the PDF with the new link, thanks for pointing that out!

I am not sure where your second statement would fit so I did not add it for now. Is it a big enough change that it would need to be approved by the Steering Committee?

[Matchmaker Exchange Service Requirements_Nov2017.pdf](https://github.com/MatchmakerExchange/matchmakerexchange.github.io/files/1438937/Matchmaker.Exchange.Service.Requirements_Nov2017.pdf)

Also related to Service Requirements, this page has the original service requirements listed
http://www.matchmakerexchange.org/i_have_a_database.html

Rather than having the service requirements in two places, should we just have "I have a database to connect" link directly to the Service Requirements in the Resource Library?

**Comment by Relequestual** [comment]
No problem. I'll get that updated on the site.

Regarding the other issue: this isn't really much of a change, but just allows the disclaimer to be split out into two parts. Users should be able to easily work out what the data asserts about itself (disclaimer), and what's required to use the data (terms) with ease. Currently we just put both bits of information in the disclaimer field.

This is essentially an extension of point 6 to "disclaimer and terms" as opposed to just disclaimer. I think it clarifies that the data isn't simply provided for any use, but has conditions attached. In DECIPHER, we essentially treat this field as terms when users view results, and must click "accept" before seeing the results from each database.
